version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:2.4
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - rethinkdb_data:/apps/rethinkdb/data

volumes:
  rethinkdb_data: null